#!/usr/bin/env python3
"""
Pull Raffa & Vale's pasta workshop dates from the Bij de Roos webshop and
turn them into workshop entries for the site.

Runs in the GitHub Pages workflow right before the Jekyll build (nightly and
on every push), so the site always shows what's actually bookable:

  - every dated "Pasta making with Raffa and Vale ..." product in the shop
    (WooCommerce Store API, public, no key needed)
  - upcoming sessions only within the next WINDOW_DAYS (≈3 months); later
    ones appear by themselves as they come into range
  - past sessions are kept too, so they show under "Past events"
  - sold-out sessions are marked sold_out, few seats left are mentioned

Each session becomes _workshops/auto-bijderoos-YYYY-MM-DD-HHMM.md (git-
ignored, regenerated every build). Hand-written files in _workshops/ are
never touched. If the shop can't be reached, the script says so and exits
cleanly: the site still builds, just without the automatic dates.

Run locally:  python3 scripts/sync_bijderoos.py
"""
import datetime as dt
import glob
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request

API = "https://bijderoos.nl/wp-json/wc/store/v1/products?per_page=100&search=raffa"
WINDOW_DAYS = 92
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "_workshops")
PREFIX = "auto-bijderoos-"

MONTHS = {m: i for i, m in enumerate(
    ["january", "february", "march", "april", "may", "june", "july",
     "august", "september", "october", "november", "december"], 1)}
# "Pasta making with Raffa and Vale sunday 14 march 2027 16.00"
NAME_RE = re.compile(r"(\d{1,2})\s+([a-z]+)\s+(\d{4})\s+(\d{1,2})[.:](\d{2})", re.I)


def fetch():
    req = urllib.request.Request(API, headers={"User-Agent": "casa-schiedam.nl date sync"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r)
    except urllib.error.URLError:
        # some local Python installs lack root certificates; curl uses the system's
        out = subprocess.run(["curl", "-sfL", "--max-time", "30", "-A", "casa-schiedam.nl date sync", API],
                             capture_output=True, text=True, check=True).stdout
        return json.loads(out)


def yaml_str(s):
    return json.dumps(s, ensure_ascii=False)   # a JSON string is a valid YAML string


def clock(h, m):
    suffix = "am" if h < 12 else "pm"
    return f"{(h % 12) or 12}:{m:02d} {suffix}"


def main():
    try:
        products = fetch()
    except Exception as e:  # network, HTTP or JSON trouble: build without auto dates
        print(f"sync_bijderoos: shop not reachable ({e}); skipping automatic dates")
        return 0

    for old in glob.glob(os.path.join(OUT_DIR, PREFIX + "*.md")):
        os.remove(old)

    today = dt.date.today()
    limit = today + dt.timedelta(days=WINDOW_DAYS)
    written = []
    for p in products:
        name = p.get("name", "")
        if "raffa" not in name.lower():
            continue
        m = NAME_RE.search(name)
        if not m or m.group(2).lower() not in MONTHS:
            continue                       # the undated "parent" product
        day, month, year = int(m.group(1)), MONTHS[m.group(2).lower()], int(m.group(3))
        hour, minute = int(m.group(4)), int(m.group(5))
        date = dt.date(year, month, day)
        if date > limit:
            continue                       # beyond the 3-month window, for now

        prices = p.get("prices") or {}
        try:
            price = int(prices.get("price")) / 10 ** int(prices.get("currency_minor_unit", 2))
            price_txt = f"€{price:g} p.p."
        except (TypeError, ValueError):
            price_txt = ""

        sold_out = not p.get("is_in_stock", True)
        left = p.get("low_stock_remaining")
        if sold_out:
            seats = "sold out"
        elif left:
            seats = f"only {left} seat{'s' if left != 1 else ''} left"
        else:
            seats = "max 10 seats"

        lines = [
            "---",
            "# Generated by scripts/sync_bijderoos.py from the Bij de Roos shop.",
            "# Don't edit: it's rewritten on every build. Change the shop instead.",
            f'title: "Pasta Making with Raffa & Vale"',
            f"date: {date.isoformat()}",
            f"time: {yaml_str(clock(hour, minute))}",
            'duration: "about 3 hours"',
            "place: \"Rose Molen, Delft — the former millers' living room\"",
            f"price: {yaml_str(price_txt)}",
            f"seats: {yaml_str(seats)}",
            "tags:",
            '  - "Fresh pasta"',
            '  - "Melting Pot"',
            f"book_url: {yaml_str(p.get('permalink', ''))}",
            'book_label: "Book on Bij de Roos →"',
            f"sold_out: {'true' if sold_out else 'false'}",
            'past_note: "Thanks to everyone who rolled pasta with us!"',
            "---",
            "",
        ]
        fn = os.path.join(OUT_DIR, f"{PREFIX}{date.isoformat()}-{hour:02d}{minute:02d}.md")
        with open(fn, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        written.append(f"{date} {hour:02d}:{minute:02d}{' (sold out)' if sold_out else ''}")

    print(f"sync_bijderoos: {len(written)} session(s) up to {limit}:")
    for w in sorted(written):
        print("  ", w)
    return 0


if __name__ == "__main__":
    sys.exit(main())
